[package]
name = "usb_whisperer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
thiserror = "1.0"
ctrlc = "3.1.7"
log = "0.4.14"
serialport = "4.0"
anyhow = "1.0.43"
